# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('EmWin_Demo', src, depend = ['EmWin_Demo'], CPPPATH = CPPPATH)

Return('group')
