import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
OS/GUI_X_OS.c
""")

src += Glob('Config/*.c')
src += Glob('Lib/*.lib')

path = [cwd + '/Config', 
		cwd + '/inc']
		
group = DefineGroup('STemWin', src, depend = ['STemWin'], CPPPATH = path)

Return('group')
