# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('HardWare', src, depend = ['TFT'], CPPPATH = CPPPATH)

Return('group')
