# RT-Thread building script for bridge

import os
from building import *

cwd = GetCurrentDir()
objs = []
src = []
list = os.listdir(cwd)
CPPPATH = [cwd]

group = DefineGroup('HardWare', src, depend = [], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
