# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('WindowDLG', src, depend = ['STemWin'], CPPPATH = CPPPATH)

Return('group')
